const coreActionType={
    FETCH_PRODUCTS_START:"FETCH_PRODUCTS_START",
    FETCH_PRODUCTS_BYSELL_SUCCESS:"FETCH_PRODUCTS_BYSELL_SUCCESS",
    FETCH_PRODUCTS_BYARRIVAL_SUCCESS:"FETCH_PRODUCTS_BYARRIVAL_SUCCESS",
    FETCH_PRODUCTS_FAILURE:"FETCH_PRODUCTS_FAILURE",
    
    GET_PRODUCT_START:'GET_PRODUCT_START',
    GET_PRODUCT_SUCCESS:'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE:'GET_PRODUCT_FAILURE',

    GET_RELATED_START:'GET_RELATED_START',
    GET_RELATED_SUCCESS:'GET_RELATED_SUCCESS',
    GET_RELATED_FAILURE:'GET_RELATED_FAILURE',
    
    
    GET_CATEGORIES_START:'GET_CATEGORIES_START',
    SET_CATEGORIES:'SET_CATEGORIES',
    SET_CATEGORIES_FAILURE:'SET_CATEGORIES_FAILURE',

    FETCH_FILTERS_START:'FETCH_FILTERS_START',
    FETCH_FILTERS_SUCCESS:'FETCH_FILTERS_SUCCESS',
    FETCH_FILTERS_FAILURE:'FETCH_FILTERS_FAILURE',

    LOAD_MORE_START:'LOAD_MORE_START',
    LOAD_MORE_SUCCESS:'LOAD_MORE_SUCCESS',
    LOAD_MORE_FAILURE:'LOAD_MORE_FAILURE',

    SEARCH_START:'SEARCH_START',
    SEARCH_SUCCESS:'SEARCH_SUCCESS',
    SEARCH_FAILURE:'SEARCH_FAILURE'
}

export default coreActionType;