const authActiontype={
    SIGNUP_START:"SIGNUP_START",
    SIGNUP_REQUESTING:"SIGNUP_REQUESTING",
    EMAIL_VERIFIED:"EMAIL_VERIFIED",
    EMAIL_VERIFICATION_FAILED:"EMAIL_VERIFICATION_FAILED",
    SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
    SIGNUP_FAILURE:"SIGNUP_FAILURE",

    RESET_REQUEST_START:"RESET_REQUEST_START",
    RESET_REQUEST_SUCCESS:"RESET_REQUEST_SUCCESS",
    RESET_PASSWORD:"RESET_PASSWORD",
    RESET_PASSWORD_SUCCESS:"RESET_PASSWORD_SUCCESS",

    SIGNIN_START:"SIGNIN_START",
    SIGNIN_REQUESTING:"SIGNIN_REQUESTING",
    SIGNIN_SUCCESS:"SIGNIN_SUCCESS",
    SIGNIN_FAILURE:"SIGNIN_FAILURE",


    CLEAR_MESSAGE:"CLEAR_MESSAGE",
    CLEAR_ERROR:"CLEAR_ERROR",

    GOOGLE_AUTH:"GOOGLE_AUTH",
    SIGNOUT_START:"SIGNOUT_START",
    SIGNOUT_SUCCESS:"SIGNOUT_SUCCESS",
  
    VERIFY_TOKEN:"VERIFY_TOKEN"
}

export default authActiontype;