const authActiontype={
    SIGNUP_START:"SIGNUP_START",
    SIGNUP_COMPLETE:"SIGNUP_COMPLETE",
    EMAIL_VERIFIED:"EMAIL_VERIFIED",
    EMAIL_VERIFICATION_FAILED:"EMAIL_VERIFICATION_FAILED",
    SIGNUP_FAILURE:"SIGNUP_FAILURE",
    SIGNIN_START:"SIGNIN_START",
    SIGNIN_SUCCESS:"SIGNIN_SUCCESS",
    SIGNIN_FAILURE:"SIGNIN_FAILURE",
    CLEAR_MESSAGE:"CLEAR_MESSAGE",
    GOOGLE_AUTH:"GOOGLE_AUTH",
    SIGNOUT_START:"SIGNOUT_START",
    SIGNOUT_SUCCESS:"SIGNOUT_SUCCESS",
    SIGNUP_MSGCLEAR:"SIGNUP_MSGCLEAR",
    SIGNIN_MSGCLEAR:"SIGNIN_MSGCLEAR",
    SIGNOUT_MSGCLEAR:"SIGNOUT_MSGCLEAR",
    VERIFY_MSGCLEAR:"VERIFY_MSGCLEAR",
    VERIFY_TOKEN:"VERIFY_TOKEN"
}

export default authActiontype;