const adminActionType={

    CREATE_CATEGORY_START:'CREATE_CATEGORY_START',
    CREATE_CATEGORY_REQUESTING:'CREATE_CATEGORY_REQUESTING',
    CREATE_CATEGORY_SUCCESS:'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILURE:'CREATE_CATEGORY_FAILURE',

    CREATE_PRODUCT_START:'CREATE_PRODUCT_START',
    CREATE_PRODUCT_REQUESTING:'CREATE_PRODUCT_REQUESTING',
    CREATE_PRODUCT_SUCCESS:'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILURE:'CREATE_PRODUCT_FAILURE',

    ADMIN_PRODUCT_SUCCESS:'ADMIN_PRODUCT_SUCCESS',

    UPDATE_PRODUCT_START:'UPDATE_PRODUCT_START',
    UPDATE_PRODUCT_SUCCESS:'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE:'UPDATE_PRODUCT_FAILURE',

    DELETE_PRODUCT_START:'DELETE_PRODUCT_START',
    DELETE_PRODUCT_SUCCESS:'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE:'DELETE_PRODUCT_FAILURE',

    ORDERS_START:'ORDERS_START',
    ORDERS_SUCCESS:'ORDERS_SUCCESS',

    CLEAR_MESSAGE:'CLEAR_MESSAGE',
    CLEAR_ERROR:'CLEAR_ERROR'
    

}

export default adminActionType;