const userActionType={
    DASH_GET_START:'DASH_GET_START',
    DASH_GET_SUCCESS:'DASH_GET_SUCCESS',

    GET_ADDRESS_START:'GET_ADDRESS_START',
    GET_ADDRESS_SUCCESS:'GET_ADDRESS_SUCCESS',
    GET_ADDRESS_FAILURE:'GET_ADDRESS_FAILURE',

    SET_ADDRESS_START:'SET_ADDRESS_START',
    SET_ADDRESS_SUCCESS:'SET_ADDRESS_SUCCESS',
    SET_ADDRESS_FAILURE:'SET_ADDRESS_FAILURE',

    UPDATE_ADDRESS_START:'UPDATE_ADDRESS_START',
    UPDATE_ADDRESS_SUCCESS:'UPDATE_ADDRESS_SUCCESS',
    UPDATE_ADDRESS_FAILURE:'UPDATE_ADDRESS_FAILURE',

    DELETE_ADDRESS_START:'DELETE_ADDRESS_START',
    DELETE_ADDRESS_SUCCESS:'DELETE_ADDRESS_SUCCESS',
    DELETE_ADDRESS_FAILURE:'DELETE_ADDRESS_FAILURE',

    OPEN_FORM:"OPEN_FORM",
    OPEN_EDIT:"OPEN_EDIT",
    CLOSE_FORM:"CLOSE_FORM",

    CLEAR_MESSAGE:'CLEAR_MESSAGE'
}

export default userActionType;